-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cooperativa
(
    rif_cooperativa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    ubicacion character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    horario character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cooperativa_pkey PRIMARY KEY (rif_cooperativa)
);

CREATE TABLE IF NOT EXISTS public.incidencias
(
    incidencias_id serial NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT incidencias_pkey PRIMARY KEY (incidencias_id)
);

CREATE TABLE IF NOT EXISTS public.licencia
(
    licencia character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fechav date,
    tipo_licencia character varying(50) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT licencia_pkey PRIMARY KEY (licencia)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    cedula character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    apellido character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    telefono character varying(50) COLLATE pg_catalog."default",
    edad integer,
    CONSTRAINT persona_pkey PRIMARY KEY (cedula)
);

CREATE TABLE IF NOT EXISTS public.ruta
(
    numero_ruta character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    tarifa integer,
    cooperativa_id character varying(50) COLLATE pg_catalog."default",
    origen_id integer,
    destino_id integer,
    CONSTRAINT ruta_pkey PRIMARY KEY (numero_ruta)
);

CREATE TABLE IF NOT EXISTS public.rutacontrol
(
    id_control serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    ubicacion character varying(50) COLLATE pg_catalog."default",
    lactitud double precision,
    longitud double precision,
    CONSTRAINT rutacontrol_pkey PRIMARY KEY (id_control)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default",
    contrasena character varying(256) COLLATE pg_catalog."default",
    rol character varying(50) COLLATE pg_catalog."default",
    status boolean,
    cedula_id character varying(50) COLLATE pg_catalog."default",
    cooperativa_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT usuario_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.vehiculos
(
    placa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(50) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    anofabricacion date,
    cooperativa_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT vehiculos_pkey PRIMARY KEY (placa)
);

CREATE TABLE IF NOT EXISTS public.viaje
(
    id_viaje serial NOT NULL,
    fecha_inicio timestamp without time zone,
    fecha_final timestamp without time zone,
    lactitud double precision,
    longitud double precision,
    user_id integer,
    vehiculo_id character varying(50) COLLATE pg_catalog."default",
    ruta_id character varying(50) COLLATE pg_catalog."default",
    incidencia_id integer,
    CONSTRAINT viaje_pkey PRIMARY KEY (id_viaje)
);

ALTER TABLE IF EXISTS public.licencia
    ADD CONSTRAINT licencia_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ruta
    ADD CONSTRAINT ruta_cooperativa_id_fkey FOREIGN KEY (cooperativa_id)
    REFERENCES public.cooperativa (rif_cooperativa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ruta
    ADD CONSTRAINT ruta_destino_id_fkey FOREIGN KEY (destino_id)
    REFERENCES public.rutacontrol (id_control) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ruta
    ADD CONSTRAINT ruta_origen_id_fkey FOREIGN KEY (origen_id)
    REFERENCES public.rutacontrol (id_control) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_cedula_id_fkey FOREIGN KEY (cedula_id)
    REFERENCES public.persona (cedula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_cooperativa_id_fkey FOREIGN KEY (cooperativa_id)
    REFERENCES public.cooperativa (rif_cooperativa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vehiculos
    ADD CONSTRAINT vehiculos_cooperativa_id_fkey FOREIGN KEY (cooperativa_id)
    REFERENCES public.cooperativa (rif_cooperativa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_incidencia_id_fkey FOREIGN KEY (incidencia_id)
    REFERENCES public.incidencias (incidencias_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_ruta_id_fkey FOREIGN KEY (ruta_id)
    REFERENCES public.ruta (numero_ruta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.usuario (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_vehiculo_id_fkey FOREIGN KEY (vehiculo_id)
    REFERENCES public.vehiculos (placa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;